# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '12_seguridad_de_operaciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 609)
        MainWindow.setStyleSheet("background-color: rgb(9, 154, 194);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 110, 611, 61))
        self.label.setStyleSheet("font: 16pt \"Arial\";")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(320, 180, 431, 371))
        self.textBrowser.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 450, 141, 51))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(180, 87, 98);\n"
"    font: 12pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 107, 118); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 67, 78); /* Color cuando el botón está presionado */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 10, 551, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Imagenes/logo segundo panel.jpg"))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 240, 201, 21))
        self.checkBox.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 270, 271, 17))
        self.checkBox_2.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 300, 271, 21))
        self.checkBox_3.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 330, 261, 21))
        self.checkBox_4.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 380, 141, 51))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(203, 246, 255);\n"
"    font: 12pt \"Arial\";\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 230, 255); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 220, 255); /* Color cuando el botón está presionado */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 560, 81, 21))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 192, 192);\n"
"    font: 11pt \"Arial\";\n"
"    color: rgb(0, 0, 0); /* Color del texto negro por defecto */\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 212, 212); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(172, 172, 172); /* Color cuando el botón está presionado */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 200, 211, 31))
        self.checkBox_5.setStyleSheet("font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 255); /* Blanco */\n"
"")
        self.checkBox_5.setObjectName("checkBox_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(320, 560, 341, 23))
        self.progressBar.setStyleSheet("font: 12pt \"Arial\";")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textBrowser, self.pushButton_5)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Módulo Pruebas 12. Seguridad de Las Operaciones"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Pruebas 12.Seguridad en las Operaciones.</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Guardar Reporte "))
        self.checkBox.setText(_translate("MainWindow", "12.3 Copias de respaldo "))
        self.checkBox_2.setText(_translate("MainWindow", "12.3.1 Respaldo  de la información "))
        self.checkBox_3.setText(_translate("MainWindow", "12.4 Registro  y seguimiento "))
        self.checkBox_4.setText(_translate("MainWindow", "12.4.1 Registro de eventos"))
        self.pushButton_6.setText(_translate("MainWindow", "Ejecutar Prueba"))
        self.pushButton_2.setText(_translate("MainWindow", "Regresar"))
        self.checkBox_5.setText(_translate("MainWindow", "Seleccionar Todo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
