# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modulo_Pruebas_de_Red.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 565)
        MainWindow.setStyleSheet("background-color: rgb(9, 154, 194);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(350, 180, 321, 331))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(50, 460, 171, 51))
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"    background-color: rgb(180, 87, 98);\n"
"    font: 12pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 107, 118); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 67, 78); /* Color cuando el botón está presionado */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 130, 371, 31))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 321, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Imagenes/Pruebas Generales.jpg"))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 220, 261, 17))
        self.checkBox.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 250, 241, 17))
        self.checkBox_2.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 280, 311, 17))
        self.checkBox_3.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 300, 301, 31))
        self.checkBox_4.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 330, 301, 31))
        self.checkBox_5.setStyleSheet("font: 12pt \"Arial\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 390, 171, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(203, 246, 255);\n"
"    font: 12pt \"Arial\";\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 230, 255); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 220, 255); /* Color cuando el botón está presionado */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 520, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 192, 192);\n"
"    font: 11pt \"Arial\";\n"
"    color: rgb(0, 0, 0); /* Color del texto negro por defecto */\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 212, 212); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(172, 172, 172); /* Color cuando el botón está presionado */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(350, 520, 231, 23))
        self.progressBar.setStyleSheet("font: 12pt \"Arial\";")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 190, 171, 16))
        self.checkBox_6.setStyleSheet("font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 255); /* Blanco */")
        self.checkBox_6.setObjectName("checkBox_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Módulo  Pruebas de Red"))
        self.pushButton_23.setText(_translate("MainWindow", "Guardar Reporte "))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Pruebas de Red</span></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Estado Del Tráfico De Red "))
        self.checkBox_2.setText(_translate("MainWindow", "Mostrar Información De Red "))
        self.checkBox_3.setText(_translate("MainWindow", "Lista De Las Conexiones De Red Activas "))
        self.checkBox_4.setText(_translate("MainWindow", "Verificar Restricciones En El Host "))
        self.checkBox_5.setText(_translate("MainWindow", "Verificar Conectividad a Internet "))
        self.pushButton.setText(_translate("MainWindow", "Ejecutar Prueba"))
        self.pushButton_2.setText(_translate("MainWindow", "Regresar"))
        self.checkBox_6.setText(_translate("MainWindow", "Seleccionar Todos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
