# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Segunda_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 671)
        MainWindow.setStyleSheet("background-color: rgb(9, 154, 194);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_V2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_V2.setGeometry(QtCore.QRect(50, 400, 301, 71))
        self.pushButton_V2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(203, 246, 255);\n"
"    font: 12pt \"Arial\";\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 230, 255); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 220, 255); /* Color cuando el botón está presionado */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_V2.setObjectName("pushButton_V2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 480, 301, 71))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(203, 246, 255);\n"
"    font: 12pt \"Arial\";\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 230, 255); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 220, 255); /* Color cuando el botón está presionado */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 480, 301, 71))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(180, 87, 98);\n"
"    font: 12pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 107, 118); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 67, 78); /* Color cuando el botón está presionado */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 130, 651, 231))
        self.label.setObjectName("label")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(380, 400, 301, 71))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(203, 246, 255);\n"
"    font: 12pt \"Arial\";\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 230, 255); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(150, 220, 255); /* Color cuando el botón está presionado */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 641, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Imagenes/logo segundo panel.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 560, 171, 61))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 192, 192);\n"
"    font: 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0); /* Color del texto negro por defecto */\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 212, 212); /* Color cuando el cursor está sobre el botón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(172, 172, 172); /* Color cuando el botón está presionado */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Módulo Auditoria"))
        self.pushButton_V2.setText(_translate("MainWindow", "9. Control de Acceso"))
        self.pushButton_3.setText(_translate("MainWindow", "13. Seguridad en las telecomunicaciones "))
        self.pushButton_5.setText(_translate("MainWindow", "Modulo de Reportes "))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">AUDITORIA</span></p><p><span style=\" font-size:12pt;\">La norma ISO 27001 aborda los dominios y objetos de control en los Numerales </span></p><p><span style=\" font-family:\'Symbol\'; font-size:12pt;\">·</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\"/><span style=\" font-size:12pt;\"> 9 (Control de Acceso)</span></p><p><span style=\" font-family:\'Symbol\'; font-size:12pt;\">·</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\"/><span style=\" font-size:12pt;\">12 (Seguridad en la Operatividad) </span></p><p><span style=\" font-family:\'Symbol\'; font-size:12pt;\">·</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\"/><span style=\" font-size:12pt;\">13 (Seguridad en las Telecomunicaciones). </span></p><p><span style=\" font-size:12pt;\">Este estándar internacional proporciona un marco para la implementación de Sistemas </span></p><p><span style=\" font-size:12pt;\">de Gestión de Seguridad de la Información (SGSI). </span></p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "12. Seguridad en las operatividad"))
        self.pushButton_2.setText(_translate("MainWindow", "Inicio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
