# Generated by Django 5.0.4 on 2024-05-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporte_equipo_alter_reporte_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='datos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
